language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

before_script:
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml
    - travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v

notifications:
    email:
        - antalaron@antalaron.hu

cache:
    directories:
        - $HOME/.composer/cache
